name: ScoreCard
description: ScoreCard is a test reporter, reporting results as a comment in your github actions.
author: Duncan Scuffell <duncanscu@gmail.com>
inputs:
  token:
    description: GitHub Access Token
    required: false
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'dist/index.js'
